
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 19 10:58:16 BRT 2018
//----------------------------------------------------

package syntax;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int LEFT_ASSIGN = 48;
  public static final int IDENTIFIER = 78;
  public static final int BLANK_IDENTIFIER = 79;
  public static final int AND_NOT_OP = 60;
  public static final int OR_OP = 55;
  public static final int GT = 36;
  public static final int TYPE = 21;
  public static final int GO = 9;
  public static final int CONST = 17;
  public static final int INT_LITERAL = 75;
  public static final int FUNC = 4;
  public static final int DEFER = 8;
  public static final int INC_OP = 58;
  public static final int COMMA = 62;
  public static final int PAR_R = 68;
  public static final int LT = 32;
  public static final int PAR_L = 67;
  public static final int CURLY_R = 72;
  public static final int STRUCT = 11;
  public static final int CURLY_L = 71;
  public static final int NOT = 40;
  public static final int XOR_ASSIGN = 46;
  public static final int VAR = 26;
  public static final int ADDRESS = 28;
  public static final int GOTO = 14;
  public static final int RUNE_LITERAL = 76;
  public static final int PACKAGE = 15;
  public static final int MUL = 34;
  public static final int RIGHT_ASSIGN = 51;
  public static final int MOD = 39;
  public static final int SUB_OP = 59;
  public static final int SELECT = 6;
  public static final int FALLTHROUGH = 18;
  public static final int ADD_ASSIGN = 41;
  public static final int IMG_LITERAL = 74;
  public static final int PLUS = 27;
  public static final int AND_NOT_ASSIGN = 52;
  public static final int MUL_ASSIGN = 45;
  public static final int ASSIGN = 49;
  public static final int INTERFACE = 5;
  public static final int CHANNEL_OP = 61;
  public static final int CHAN = 12;
  public static final int SWITCH = 16;
  public static final int FOR = 23;
  public static final int MINUS_ASSIGN = 43;
  public static final int DIV = 38;
  public static final int RETURN = 25;
  public static final int ELSE = 13;
  public static final int BREAK = 2;
  public static final int DOT = 66;
  public static final int MAP = 10;
  public static final int LTE = 33;
  public static final int STRING_LITERAL = 73;
  public static final int EOF = 0;
  public static final int SEMICOLON = 63;
  public static final int DEFAULT = 3;
  public static final int IMPORT = 24;
  public static final int MINUS = 30;
  public static final int FLOAT_LITERAL = 77;
  public static final int OR = 31;
  public static final int error = 1;
  public static final int RIGHT_OP = 57;
  public static final int OR_ASSIGN = 44;
  public static final int GTE = 37;
  public static final int CONTINUE = 22;
  public static final int IF = 19;
  public static final int DIV_ASSIGN = 47;
  public static final int SQRD_R = 70;
  public static final int COLON = 65;
  public static final int SQRD_L = 69;
  public static final int CHANNEL_ASSIGN = 50;
  public static final int ADDRESS_ASSIGN = 42;
  public static final int NE_OP = 54;
  public static final int CASE = 7;
  public static final int EQ_OP = 53;
  public static final int RANGE = 20;
  public static final int AND = 29;
  public static final int ELLIPSIS = 64;
  public static final int LEFT_OP = 56;
  public static final int XOR = 35;
}

