/* The following code was generated by JFlex 1.3.5 on 03/06/18 15:35 */

package lexical;

import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import syntax.Sym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 03/06/18 15:35 from the specification file
 * <tt>file:/home/carolws/eclipse-workspace/GoCompiler/core/src/lexical/language.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner, Sym {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\41\1\2\1\0\1\41\1\1\22\0\1\41\1\65\1\4"+
    "\1\100\1\0\1\64\1\57\1\40\1\67\1\70\1\43\1\22\1\75"+
    "\1\23\1\24\1\42\1\12\7\15\2\11\1\66\1\76\1\60\1\61"+
    "\1\63\1\77\1\0\4\13\1\21\1\13\16\6\1\30\2\6\1\17"+
    "\2\6\1\71\1\26\1\72\1\62\1\10\1\5\1\31\1\32\1\14"+
    "\1\45\1\20\1\33\1\50\1\54\1\25\1\6\1\44\1\46\1\52"+
    "\1\34\1\51\1\53\1\6\1\35\1\47\1\36\1\27\1\37\1\55"+
    "\1\16\1\56\1\6\1\73\1\3\1\74\54\0\1\6\12\0\1\6"+
    "\4\0\1\6\5\0\27\6\1\0\37\6\1\0\u01ca\6\4\0\14\6"+
    "\16\0\5\6\7\0\1\6\1\0\1\6\201\0\5\6\1\0\2\6"+
    "\2\0\4\6\10\0\1\6\1\0\3\6\1\0\1\6\1\0\24\6"+
    "\1\0\123\6\1\0\213\6\10\0\236\6\11\0\46\6\2\0\1\6"+
    "\7\0\47\6\110\0\33\6\5\0\3\6\55\0\53\6\25\0\12\7"+
    "\4\0\2\6\1\0\143\6\1\0\1\6\17\0\2\6\7\0\2\6"+
    "\12\7\3\6\2\0\1\6\20\0\1\6\1\0\36\6\35\0\131\6"+
    "\13\0\1\6\16\0\12\7\41\6\11\0\2\6\4\0\1\6\5\0"+
    "\26\6\4\0\1\6\11\0\1\6\3\0\1\6\27\0\31\6\107\0"+
    "\1\6\1\0\13\6\127\0\66\6\3\0\1\6\22\0\1\6\7\0"+
    "\12\6\4\0\12\7\1\0\7\6\1\0\7\6\5\0\10\6\2\0"+
    "\2\6\2\0\26\6\1\0\7\6\1\0\1\6\3\0\4\6\3\0"+
    "\1\6\20\0\1\6\15\0\2\6\1\0\3\6\4\0\12\7\2\6"+
    "\23\0\6\6\4\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6"+
    "\1\0\2\6\1\0\2\6\37\0\4\6\1\0\1\6\7\0\12\7"+
    "\2\0\3\6\20\0\11\6\1\0\3\6\1\0\26\6\1\0\7\6"+
    "\1\0\2\6\1\0\5\6\3\0\1\6\22\0\1\6\17\0\2\6"+
    "\4\0\12\7\25\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6"+
    "\1\0\2\6\1\0\5\6\3\0\1\6\36\0\2\6\1\0\3\6"+
    "\4\0\12\7\1\0\1\6\21\0\1\6\1\0\6\6\3\0\3\6"+
    "\1\0\4\6\3\0\2\6\1\0\1\6\1\0\2\6\3\0\2\6"+
    "\3\0\3\6\3\0\14\6\26\0\1\6\25\0\12\7\25\0\10\6"+
    "\1\0\3\6\1\0\27\6\1\0\12\6\1\0\5\6\3\0\1\6"+
    "\32\0\2\6\6\0\2\6\4\0\12\7\25\0\10\6\1\0\3\6"+
    "\1\0\27\6\1\0\12\6\1\0\5\6\3\0\1\6\40\0\1\6"+
    "\1\0\2\6\4\0\12\7\1\0\2\6\22\0\10\6\1\0\3\6"+
    "\1\0\51\6\2\0\1\6\20\0\1\6\21\0\2\6\4\0\12\7"+
    "\12\0\6\6\5\0\22\6\3\0\30\6\1\0\11\6\1\0\1\6"+
    "\2\0\7\6\72\0\60\6\1\0\2\6\14\0\7\6\11\0\12\7"+
    "\47\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6\2\0\1\6"+
    "\6\0\4\6\1\0\7\6\1\0\3\6\1\0\1\6\1\0\1\6"+
    "\2\0\2\6\1\0\4\6\1\0\2\6\11\0\1\6\2\0\5\6"+
    "\1\0\1\6\11\0\12\7\2\0\4\6\40\0\1\6\37\0\12\7"+
    "\26\0\10\6\1\0\44\6\33\0\5\6\163\0\53\6\24\0\1\6"+
    "\12\7\6\0\6\6\4\0\4\6\3\0\1\6\3\0\2\6\7\0"+
    "\3\6\4\0\15\6\14\0\1\6\1\0\12\7\6\0\46\6\1\0"+
    "\1\6\5\0\1\6\2\0\53\6\1\0\u014d\6\1\0\4\6\2\0"+
    "\7\6\1\0\1\6\1\0\4\6\2\0\51\6\1\0\4\6\2\0"+
    "\41\6\1\0\4\6\2\0\7\6\1\0\1\6\1\0\4\6\2\0"+
    "\17\6\1\0\71\6\1\0\4\6\2\0\103\6\45\0\20\6\20\0"+
    "\125\6\14\0\u026c\6\2\0\21\6\1\0\32\6\5\0\113\6\25\0"+
    "\15\6\1\0\4\6\16\0\22\6\16\0\22\6\16\0\15\6\1\0"+
    "\3\6\17\0\64\6\43\0\1\6\4\0\1\6\3\0\12\7\46\0"+
    "\12\7\6\0\130\6\10\0\51\6\1\0\1\6\5\0\106\6\12\0"+
    "\35\6\51\0\12\7\36\6\2\0\5\6\13\0\54\6\25\0\7\6"+
    "\10\0\12\7\46\0\27\6\11\0\65\6\53\0\12\7\6\0\12\7"+
    "\15\0\1\6\135\0\57\6\21\0\7\6\4\0\12\7\51\0\36\6"+
    "\15\0\2\6\12\7\54\6\32\0\44\6\34\0\12\7\3\0\3\6"+
    "\12\7\44\6\153\0\4\6\1\0\4\6\3\0\2\6\11\0\300\6"+
    "\100\0\u0116\6\2\0\6\6\2\0\46\6\2\0\6\6\2\0\10\6"+
    "\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6\2\0\65\6"+
    "\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6\3\0\4\6"+
    "\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6\164\0\1\6"+
    "\15\0\1\6\20\0\15\6\145\0\1\6\4\0\1\6\2\0\12\6"+
    "\1\0\1\6\3\0\5\6\6\0\1\6\1\0\1\6\1\0\1\6"+
    "\1\0\4\6\1\0\13\6\2\0\4\6\5\0\5\6\4\0\1\6"+
    "\64\0\2\6\u0a7b\0\57\6\1\0\57\6\1\0\205\6\6\0\4\6"+
    "\3\0\2\6\14\0\46\6\1\0\1\6\5\0\1\6\2\0\70\6"+
    "\7\0\1\6\20\0\27\6\11\0\7\6\1\0\7\6\1\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6"+
    "\120\0\1\6\u01d5\0\2\6\52\0\5\6\5\0\2\6\4\0\126\6"+
    "\6\0\3\6\1\0\132\6\1\0\4\6\5\0\51\6\3\0\136\6"+
    "\21\0\33\6\65\0\20\6\u0200\0\u19b6\6\112\0\u51cd\6\63\0\u048d\6"+
    "\103\0\56\6\2\0\u010d\6\3\0\20\6\12\7\2\6\24\0\57\6"+
    "\20\0\31\6\10\0\106\6\61\0\11\6\2\0\147\6\2\0\4\6"+
    "\1\0\4\6\14\0\13\6\115\0\12\6\1\0\3\6\1\0\4\6"+
    "\1\0\27\6\35\0\64\6\16\0\62\6\34\0\12\7\30\0\6\6"+
    "\3\0\1\6\4\0\12\7\34\6\12\0\27\6\31\0\35\6\7\0"+
    "\57\6\34\0\1\6\12\7\46\0\51\6\27\0\3\6\1\0\10\6"+
    "\4\0\12\7\6\0\27\6\3\0\1\6\5\0\60\6\1\0\1\6"+
    "\3\0\2\6\2\0\5\6\2\0\1\6\1\0\1\6\30\0\3\6"+
    "\2\0\13\6\7\0\3\6\14\0\6\6\2\0\6\6\2\0\6\6"+
    "\11\0\7\6\1\0\7\6\221\0\43\6\15\0\12\7\6\0\u2ba4\6"+
    "\14\0\27\6\4\0\61\6\u2104\0\u016e\6\2\0\152\6\46\0\7\6"+
    "\14\0\5\6\5\0\1\6\1\0\12\6\1\0\15\6\1\0\5\6"+
    "\1\0\1\6\1\0\2\6\1\0\2\6\1\0\154\6\41\0\u016b\6"+
    "\22\0\100\6\2\0\66\6\50\0\14\6\164\0\5\6\1\0\207\6"+
    "\23\0\12\7\7\0\32\6\6\0\32\6\13\0\131\6\3\0\6\6"+
    "\2\0\6\6\2\0\6\6\2\0\3\6\43\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    65,   130,    65,   195,   260,   325,   390,   390,   455, 
      520,   585,   650,   715,   780,   845,   910,   975,  1040,  1105, 
     1170,  1235,  1300,  1365,  1430,  1495,  1560,  1625,  1690,  1755, 
     1820,  1885,  1950,  2015,  2080,    65,  2145,  2210,    65,    65, 
       65,    65,    65,    65,    65,    65,  2275,    65,    65,    65, 
      260,    65,  2340,   325,  2405,  2470,  2535,  2405,  2600,  2665, 
     2730,  2795,  2860,  2925,  2990,    65,    65,    65,    65,  3055, 
      390,  3120,  3185,  3250,  3315,  3380,  3445,  3510,  3575,  3640, 
     3705,  3770,  3835,  3900,  3965,  4030,    65,    65,  4095,  4160, 
     4225,  4290,  4355,  4420,  4485,    65,    65,  4550,    65,  4615, 
       65,    65,    65,    65,  4680,    65,    65,    65,   260,  4745, 
     4810,  4875,    65,  2730,  4940,  5005,  5070,  5135,    65,  5200, 
     5265,  5330,  5395,  5460,   390,  5525,  5590,  5655,  5720,   390, 
       65,  5785,  5850,  5915,  5980,  3835,  6045,    65,  6110,  6175, 
     6240,  6305,  6370,  6435,  6500,   390,  6565,    65,    65,    65, 
     6630,   390,  6695,  6760,   390,   390,  6825,  6890,  6955,   390, 
     7020,  7085,  7150,  7215,   390,   390,  7280,  7345,  7410,  7475, 
       65,  7540,  7605,  7670,  7735,  7800,   390,  7865,  7930,   390, 
     7995,  8060,   390,  8125,   390,  8190,   390,  8255,   390,  8320, 
     8385,  8450,  8515,  8580,  8645,  8710,   390,  8775,   390,  8840, 
     8905,   390,   390,   390,  8970,  9035,  9100,  9165,   390,   390, 
      390,  9230,  9295,   390,  9360,  9425,   390
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\1\13\1\10\1\14\1\12\2\10\1\15"+
    "\1\10\1\16\1\17\1\20\1\21\1\2\3\10\1\22"+
    "\1\23\1\10\1\24\1\25\1\26\1\27\1\4\1\30"+
    "\1\31\1\10\1\32\1\10\1\33\1\34\1\10\1\35"+
    "\1\36\3\10\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\103\0\1\4\101\0\1\61"+
    "\55\0\1\62\17\0\1\63\3\0\1\64\21\63\1\65"+
    "\52\63\3\66\1\0\1\66\1\64\73\66\6\0\14\10"+
    "\3\0\1\10\1\0\11\10\4\0\13\10\30\0\1\67"+
    "\1\0\1\67\2\12\2\67\1\12\2\67\2\70\2\0"+
    "\1\71\1\72\1\0\11\67\4\0\13\67\30\0\1\67"+
    "\1\0\1\67\1\73\1\74\2\67\1\74\2\75\2\70"+
    "\2\0\1\71\1\72\1\0\11\67\4\0\13\67\30\0"+
    "\14\10\3\0\1\10\1\0\2\10\1\76\6\10\4\0"+
    "\5\10\1\77\2\10\1\100\2\10\30\0\14\10\3\0"+
    "\1\10\1\0\11\10\4\0\2\10\1\101\10\10\44\0"+
    "\1\102\36\0\1\103\42\0\1\104\35\0\1\105\30\0"+
    "\2\71\2\0\1\71\6\0\1\106\62\0\14\10\3\0"+
    "\1\10\1\0\4\10\1\107\1\110\3\10\4\0\6\10"+
    "\1\111\4\10\30\0\14\10\3\0\1\10\1\0\6\10"+
    "\1\112\2\10\4\0\13\10\30\0\14\10\3\0\1\10"+
    "\1\0\1\113\1\10\1\114\6\10\4\0\5\10\1\115"+
    "\5\10\30\0\12\10\1\116\1\10\3\0\1\10\1\0"+
    "\2\10\1\117\6\10\4\0\13\10\30\0\14\10\3\0"+
    "\1\10\1\0\6\10\1\120\2\10\4\0\12\10\1\121"+
    "\30\0\14\10\3\0\1\10\1\0\2\10\1\122\6\10"+
    "\4\0\13\10\22\0\1\123\3\0\22\123\1\124\52\123"+
    "\42\0\1\125\1\126\15\0\1\127\100\0\1\130\25\0"+
    "\12\10\1\131\1\10\3\0\1\10\1\0\11\10\4\0"+
    "\13\10\30\0\12\10\1\132\1\10\3\0\1\10\1\0"+
    "\7\10\1\133\1\10\4\0\11\10\1\134\1\10\30\0"+
    "\14\10\3\0\1\10\1\0\11\10\4\0\5\10\1\135"+
    "\5\10\30\0\14\10\3\0\1\10\1\0\2\10\1\136"+
    "\6\10\4\0\13\10\30\0\14\10\3\0\1\10\1\0"+
    "\2\10\1\137\6\10\4\0\13\10\101\0\1\140\1\0"+
    "\1\141\1\142\41\0\1\143\34\0\1\144\1\145\100\0"+
    "\1\146\100\0\1\147\100\0\1\150\1\0\1\151\76\0"+
    "\1\152\100\0\1\153\116\0\1\154\1\0\1\63\3\0"+
    "\1\155\21\63\1\65\52\63\6\0\1\67\1\0\12\67"+
    "\3\0\1\67\1\0\11\67\4\0\13\67\30\0\1\67"+
    "\1\0\1\67\2\156\2\67\1\156\4\67\2\157\1\0"+
    "\1\67\1\0\11\67\4\0\13\67\33\0\2\71\2\0"+
    "\1\71\2\0\2\160\3\0\1\161\61\0\1\67\1\0"+
    "\1\67\2\73\2\67\1\73\2\67\2\70\2\0\1\71"+
    "\1\72\1\0\11\67\4\0\13\67\30\0\1\67\1\0"+
    "\1\67\1\73\1\74\2\67\1\74\2\67\2\70\2\0"+
    "\1\71\1\72\1\0\11\67\4\0\13\67\30\0\1\67"+
    "\1\0\1\67\5\162\2\67\2\162\3\0\1\67\1\0"+
    "\2\67\3\162\4\67\4\0\1\67\1\162\11\67\30\0"+
    "\14\10\3\0\1\10\1\0\11\10\4\0\3\10\1\163"+
    "\7\10\30\0\14\10\3\0\1\10\1\0\5\10\1\164"+
    "\3\10\4\0\13\10\30\0\14\10\3\0\1\10\1\0"+
    "\2\10\1\165\6\10\4\0\13\10\30\0\14\10\3\0"+
    "\1\10\1\0\11\10\4\0\3\10\1\166\7\10\46\0"+
    "\1\167\62\0\14\10\3\0\1\10\1\0\7\10\1\170"+
    "\1\10\4\0\13\10\30\0\14\10\3\0\1\10\1\0"+
    "\11\10\4\0\7\10\1\171\3\10\30\0\12\10\1\172"+
    "\1\10\3\0\1\10\1\0\11\10\4\0\13\10\30\0"+
    "\14\10\3\0\1\10\1\0\5\10\1\173\3\10\4\0"+
    "\13\10\30\0\14\10\3\0\1\10\1\0\11\10\4\0"+
    "\2\10\1\174\10\10\30\0\14\10\3\0\1\10\1\0"+
    "\6\10\1\175\2\10\4\0\13\10\30\0\14\10\3\0"+
    "\1\10\1\0\7\10\1\176\1\10\4\0\13\10\30\0"+
    "\14\10\3\0\1\10\1\0\5\10\1\177\3\10\4\0"+
    "\13\10\30\0\14\10\3\0\1\10\1\0\1\200\10\10"+
    "\4\0\13\10\30\0\14\10\3\0\1\10\1\0\11\10"+
    "\4\0\7\10\1\201\3\10\30\0\14\10\3\0\1\10"+
    "\1\0\6\10\1\202\2\10\4\0\13\10\62\0\1\203"+
    "\44\0\1\123\5\0\1\204\2\0\1\204\1\205\7\0"+
    "\1\123\1\206\1\207\7\123\1\210\40\0\1\125\1\211"+
    "\1\212\1\213\75\125\43\126\1\214\35\126\6\0\14\10"+
    "\3\0\1\10\1\0\4\10\1\215\4\10\4\0\13\10"+
    "\30\0\14\10\3\0\1\10\1\0\11\10\4\0\2\10"+
    "\1\216\10\10\30\0\14\10\3\0\1\10\1\0\6\10"+
    "\1\217\2\10\4\0\13\10\30\0\14\10\3\0\1\220"+
    "\1\0\11\10\4\0\13\10\30\0\14\10\3\0\1\10"+
    "\1\0\7\10\1\221\1\10\4\0\13\10\30\0\14\10"+
    "\3\0\1\10\1\0\11\10\4\0\7\10\1\222\3\10"+
    "\30\0\6\10\1\223\5\10\3\0\1\10\1\0\11\10"+
    "\4\0\13\10\103\0\1\224\100\0\1\225\100\0\1\226"+
    "\25\0\1\67\1\0\1\67\2\156\2\67\1\156\4\67"+
    "\3\0\1\72\1\0\11\67\4\0\13\67\33\0\2\227"+
    "\2\0\1\227\74\0\2\227\2\0\1\227\4\0\2\157"+
    "\63\0\12\10\1\230\1\10\3\0\1\10\1\0\11\10"+
    "\4\0\13\10\30\0\14\10\3\0\1\10\1\0\7\10"+
    "\1\231\1\10\4\0\3\10\1\232\7\10\30\0\14\10"+
    "\3\0\1\10\1\0\5\10\1\233\3\10\4\0\13\10"+
    "\30\0\12\10\1\234\1\10\3\0\1\10\1\0\11\10"+
    "\4\0\13\10\30\0\12\10\1\235\1\10\3\0\1\10"+
    "\1\0\11\10\4\0\13\10\30\0\14\10\3\0\1\10"+
    "\1\0\11\10\4\0\5\10\1\236\5\10\30\0\14\10"+
    "\3\0\1\10\1\0\2\10\1\237\6\10\4\0\13\10"+
    "\30\0\6\10\1\240\5\10\3\0\1\10\1\0\11\10"+
    "\4\0\13\10\30\0\14\10\3\0\1\10\1\0\11\10"+
    "\4\0\2\10\1\241\1\242\7\10\30\0\14\10\3\0"+
    "\1\10\1\0\1\243\10\10\4\0\13\10\30\0\14\10"+
    "\3\0\1\10\1\0\11\10\4\0\4\10\1\244\6\10"+
    "\30\0\12\10\1\245\1\10\3\0\1\10\1\0\11\10"+
    "\4\0\13\10\30\0\12\10\1\246\1\10\3\0\1\10"+
    "\1\0\11\10\4\0\13\10\34\0\1\247\2\0\1\247"+
    "\74\0\5\250\2\0\2\250\7\0\3\250\11\0\1\250"+
    "\44\0\5\251\2\0\2\251\7\0\3\251\11\0\1\251"+
    "\44\0\5\252\2\0\2\252\7\0\3\252\11\0\1\252"+
    "\35\0\1\212\101\0\1\125\75\0\42\126\1\253\1\214"+
    "\35\126\6\0\12\10\1\254\1\10\3\0\1\10\1\0"+
    "\2\10\1\255\6\10\4\0\13\10\30\0\12\10\1\256"+
    "\1\10\3\0\1\10\1\0\11\10\4\0\13\10\30\0"+
    "\14\10\3\0\1\10\1\0\1\257\10\10\4\0\13\10"+
    "\30\0\14\10\3\0\1\10\1\0\7\10\1\260\1\10"+
    "\4\0\13\10\30\0\14\10\3\0\1\10\1\0\11\10"+
    "\4\0\5\10\1\261\5\10\30\0\14\10\3\0\1\10"+
    "\1\0\11\10\4\0\1\262\12\10\33\0\2\227\2\0"+
    "\1\227\7\0\1\161\61\0\14\10\3\0\1\263\1\0"+
    "\11\10\4\0\13\10\30\0\14\10\3\0\1\10\1\0"+
    "\7\10\1\264\1\10\4\0\13\10\30\0\14\10\3\0"+
    "\1\10\1\0\6\10\1\265\2\10\4\0\13\10\30\0"+
    "\14\10\3\0\1\10\1\0\6\10\1\266\2\10\4\0"+
    "\13\10\30\0\14\10\3\0\1\10\1\0\11\10\4\0"+
    "\1\267\12\10\30\0\14\10\3\0\1\10\1\0\7\10"+
    "\1\270\1\10\4\0\13\10\30\0\12\10\1\271\1\10"+
    "\3\0\1\10\1\0\11\10\4\0\13\10\30\0\14\10"+
    "\3\0\1\10\1\0\6\10\1\272\2\10\4\0\13\10"+
    "\30\0\12\10\1\273\1\10\3\0\1\10\1\0\11\10"+
    "\4\0\13\10\34\0\1\123\2\0\1\123\74\0\5\123"+
    "\2\0\2\123\7\0\3\123\11\0\1\123\44\0\5\205"+
    "\2\0\2\205\7\0\3\205\11\0\1\205\44\0\5\274"+
    "\2\0\2\274\7\0\3\274\11\0\1\274\41\0\14\10"+
    "\3\0\1\10\1\0\6\10\1\275\2\10\4\0\13\10"+
    "\30\0\14\10\3\0\1\10\1\0\1\276\10\10\4\0"+
    "\13\10\30\0\6\10\1\277\5\10\3\0\1\10\1\0"+
    "\11\10\4\0\13\10\30\0\6\10\1\300\5\10\3\0"+
    "\1\10\1\0\11\10\4\0\13\10\30\0\6\10\1\301"+
    "\5\10\3\0\1\10\1\0\11\10\4\0\13\10\30\0"+
    "\14\10\3\0\1\10\1\0\2\10\1\302\6\10\4\0"+
    "\13\10\30\0\14\10\3\0\1\10\1\0\5\10\1\303"+
    "\3\10\4\0\13\10\30\0\14\10\3\0\1\10\1\0"+
    "\4\10\1\304\4\10\4\0\13\10\30\0\14\10\3\0"+
    "\1\10\1\0\7\10\1\305\1\10\4\0\13\10\30\0"+
    "\14\10\3\0\1\10\1\0\11\10\4\0\10\10\1\306"+
    "\2\10\30\0\14\10\3\0\1\10\1\0\5\10\1\307"+
    "\3\10\4\0\13\10\33\0\5\310\2\0\2\310\7\0"+
    "\3\310\11\0\1\310\41\0\14\10\3\0\1\10\1\0"+
    "\11\10\4\0\2\10\1\311\10\10\30\0\14\10\3\0"+
    "\1\10\1\0\7\10\1\312\1\10\4\0\13\10\30\0"+
    "\14\10\3\0\1\10\1\0\7\10\1\313\1\10\4\0"+
    "\13\10\30\0\14\10\3\0\1\10\1\0\11\10\4\0"+
    "\10\10\1\314\2\10\30\0\14\10\3\0\1\10\1\0"+
    "\11\10\4\0\4\10\1\315\6\10\30\0\14\10\3\0"+
    "\1\10\1\0\1\316\10\10\4\0\13\10\30\0\14\10"+
    "\3\0\1\10\1\0\2\10\1\317\6\10\4\0\13\10"+
    "\30\0\14\10\3\0\1\10\1\0\6\10\1\320\2\10"+
    "\4\0\13\10\33\0\5\206\2\0\2\206\7\0\3\206"+
    "\11\0\1\206\41\0\14\10\3\0\1\10\1\0\7\10"+
    "\1\321\1\10\4\0\13\10\30\0\12\10\1\322\1\10"+
    "\3\0\1\10\1\0\11\10\4\0\13\10\30\0\12\10"+
    "\1\323\1\10\3\0\1\10\1\0\11\10\4\0\13\10"+
    "\30\0\6\10\1\324\5\10\3\0\1\10\1\0\11\10"+
    "\4\0\13\10\30\0\14\10\3\0\1\10\1\0\11\10"+
    "\4\0\5\10\1\325\5\10\30\0\12\10\1\326\1\10"+
    "\3\0\1\10\1\0\11\10\4\0\13\10\30\0\14\10"+
    "\3\0\1\10\1\0\1\327\10\10\4\0\13\10\30\0"+
    "\14\10\3\0\1\10\1\0\11\10\4\0\4\10\1\330"+
    "\6\10\30\0\14\10\3\0\1\10\1\0\11\10\4\0"+
    "\10\10\1\331\2\10\22\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  9,  1,  1,  9,  9,  9,  9,  9,  9,  9,  9,  1,  9, 
     9,  9,  0,  9,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  9,  9,  9,  9,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  0,  0,  1,  0,  9,  9,  1,  1,  1,  1,  1,  1,  1,  9, 
     9,  1,  9,  1,  9,  9,  9,  9,  1,  9,  9,  9,  1,  1,  0,  0, 
     9,  1,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  9,  0,  0,  0,  0,  1,  1,  9,  0,  0,  1,  1,  1,  1, 
     1,  1,  1,  9,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  9,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	ComplexSymbolFactory symbolFactory;
    public Lexer(java.io.Reader in, ComplexSymbolFactory sf){
		this(in);
		symbolFactory = sf;
    }
  
    private Symbol symbol(int sym) {
    	//System.out.println("Token " + Sym.terminalNames[sym] + ", Line: " + yyline + ", size:" + yylength());
      	return symbolFactory.newSymbol("sym", sym, new Location(yyline+1,yycolumn+1,yychar), new Location(yyline+1,yycolumn+yylength(),yychar+yylength()));
  	}
  
  	private Symbol symbol(int sym, Object val) {
  		//System.out.println("Token (" + Sym.terminalNames[sym] + ", " + val +  ") , Line: " + yyline + ", size:" + yylength());
		Location left = new Location(yyline+1,yycolumn+1,yychar);
		Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
		return symbolFactory.newSymbol("sym", sym, left, right,val);
  	}
  	
    private Symbol symbol(int sym, Object val,int buflength) {
        //System.out.println("Token (" + Sym.terminalNames[sym] + ", " + val +  ") , Line: " + yyline + ", size:" + yylength());
        Location left = new Location(yyline+1,yycolumn+yylength()-buflength,yychar+yylength()-buflength);
        Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
        return symbolFactory.newSymbol("sym", sym, left, right,val);
    }
	
	private void ignore(String pattern, String content) {
		System.out.println("Ignoring " + pattern + ", content: " + content);
	}
	
	private void reportError(String invalidPattern, int line, int column) {
		System.err.println("Lexical error: " + invalidPattern + ", line: " + line + ", column: " + column);
	}
	
	


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[9490];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1734) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 4: 
          {  return symbol(OR, "|");  }
        case 218: break;
        case 31: 
          {  return symbol(LT, "<");  }
        case 219: break;
        case 34: 
          {  return symbol(GT, ">");  }
        case 220: break;
        case 170: 
          {  ignore("Long comment", yytext());  }
        case 221: break;
        case 84: 
        case 136: 
        case 137: 
          {  ignore("Line comment", yytext());  }
        case 222: break;
        case 54: 
        case 55: 
        case 58: 
        case 60: 
          {  reportError(yytext(), yyline + 1, yycolumn + 1);  }
        case 223: break;
        case 47: 
          {  return symbol(HASH, "#");  }
        case 224: break;
        case 36: 
          {  return symbol(NOT, "!");  }
        case 225: break;
        case 13: 
          {  return symbol(PLUS, "+");  }
        case 226: break;
        case 1: 
        case 5: 
        case 6: 
        case 22: 
          {  reportError(yytext(), yyline + 1, yycolumn + 1);  }
        case 227: break;
        case 15: 
          {  return symbol(DOT, ".");  }
        case 228: break;
        case 23: 
          {  return symbol(DIV, "/");  }
        case 229: break;
        case 24: 
          {  return symbol(MUL, "*");  }
        case 230: break;
        case 33: 
          {  return symbol(XOR, "^");  }
        case 231: break;
        case 35: 
          {  return symbol(MOD, "%");  }
        case 232: break;
        case 70: 
          {  return symbol(IF, "if");  }
        case 233: break;
        case 92: 
          {  return symbol(GO, "go");  }
        case 234: break;
        case 95: 
          {  return symbol(AND, "&&");  }
        case 235: break;
        case 100: 
          {  return symbol(LTE, "<=");  }
        case 236: break;
        case 103: 
          {  return symbol(GTE, ">=");  }
        case 237: break;
        case 56: 
        case 109: 
        case 150: 
          {  return symbol(FLOAT_LITERAL, yytext());  }
        case 238: break;
        case 51: 
        case 108: 
          {  return symbol(STRING_LITERAL, yytext());  }
        case 239: break;
        case 86: 
          {  return symbol(DIV_ASSIGN, "/=");  }
        case 240: break;
        case 68: 
          {  return symbol(MINUS_ASSIGN, "-=");  }
        case 241: break;
        case 198: 
          {  return symbol(RETURN, "return");  }
        case 242: break;
        case 7: 
        case 11: 
        case 12: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 21: 
        case 25: 
        case 26: 
        case 27: 
        case 28: 
        case 29: 
        case 61: 
        case 62: 
        case 63: 
        case 64: 
        case 71: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 77: 
        case 78: 
        case 79: 
        case 80: 
        case 81: 
        case 88: 
        case 89: 
        case 90: 
        case 91: 
        case 93: 
        case 94: 
        case 114: 
        case 115: 
        case 116: 
        case 117: 
        case 119: 
        case 120: 
        case 121: 
        case 122: 
        case 123: 
        case 125: 
        case 126: 
        case 127: 
        case 128: 
        case 140: 
        case 141: 
        case 142: 
        case 143: 
        case 144: 
        case 146: 
        case 152: 
        case 153: 
        case 156: 
        case 157: 
        case 158: 
        case 160: 
        case 161: 
        case 162: 
        case 163: 
        case 171: 
        case 172: 
        case 173: 
        case 174: 
        case 175: 
        case 177: 
        case 178: 
        case 180: 
        case 181: 
        case 183: 
        case 185: 
        case 189: 
        case 190: 
        case 191: 
        case 192: 
        case 193: 
        case 194: 
        case 195: 
        case 197: 
        case 200: 
        case 204: 
        case 205: 
        case 206: 
        case 207: 
        case 211: 
        case 212: 
        case 214: 
        case 215: 
          {  return symbol(IDENTIFIER, yytext());  }
        case 243: break;
        case 148: 
          {  return symbol(LEFT_ASSIGN, "<<=");  }
        case 244: break;
        case 164: 
          {  return symbol(TRUE, "true");  }
        case 245: break;
        case 165: 
          {  return symbol(TYPE, "type");  }
        case 246: break;
        case 67: 
          {  return symbol(SUB_OP, "--");  }
        case 247: break;
        case 202: 
          {  return symbol(STRUCT, "struct");  }
        case 248: break;
        case 182: 
          {  return symbol(BREAK, "break");  }
        case 249: break;
        case 49: 
          {  return symbol(OR_ASSIGN, "|=");  }
        case 250: break;
        case 102: 
          {  return symbol(XOR_ASSIGN, "^=");  }
        case 251: break;
        case 196: 
          {  return symbol(IMPORT, "import");  }
        case 252: break;
        case 216: 
          {  return symbol(FALLTHROUGH, "fallthrough");  }
        case 253: break;
        case 179: 
          {  return symbol(CONST, "const");  }
        case 254: break;
        case 106: 
          {  return symbol(CHANNEL_ASSIGN, ":=");  }
        case 255: break;
        case 147: 
          {  return symbol(AND_NOT_ASSIGN, "&^=");  }
        case 256: break;
        case 201: 
          {  return symbol(SELECT, "select");  }
        case 257: break;
        case 57: 
        case 112: 
          {  return symbol(IMG_LITERAL, yytext());  }
        case 258: break;
        case 9: 
        case 10: 
        case 59: 
        case 113: 
          {  return symbol(INT_LITERAL, yytext());  }
        case 259: break;
        case 87: 
          {  return symbol(MUL_ASSIGN, "*=");  }
        case 260: break;
        case 99: 
          {  return symbol(LEFT_OP, "<<");  }
        case 261: break;
        case 118: 
          {  return symbol(ELLIPSIS,"...");  }
        case 262: break;
        case 130: 
        case 135: 
          {  return symbol(RUNE_LITERAL, yytext());  }
        case 263: break;
        case 209: 
          {  return symbol(PACKAGE, "package");  }
        case 264: break;
        case 8: 
          {  return symbol(BLANK_IDENTIFIER, "_");  }
        case 265: break;
        case 210: 
          {  return symbol(CONTINUE, "continue");  }
        case 266: break;
        case 203: 
          {  return symbol(SWITCH, "switch");  }
        case 267: break;
        case 65: 
          {  return symbol(INC_OP, "++");  }
        case 268: break;
        case 104: 
          {  return symbol(RIGHT_OP, ">>");  }
        case 269: break;
        case 107: 
          {  return symbol(DOUBLE_INTERROGATION, "??");  }
        case 270: break;
        case 149: 
          {  return symbol(RIGHT_ASSIGN, ">>=");  }
        case 271: break;
        case 176: 
          {  return symbol(GOTO, "goto");  }
        case 272: break;
        case 213: 
          {  return symbol(INTERFACE, "interface");  }
        case 273: break;
        case 159: 
          {  return symbol(FUNC, "func");  }
        case 274: break;
        case 188: 
          {  return symbol(DEFER, "defer");  }
        case 275: break;
        case 46: 
          {  return symbol(INTERROGATION, "?");  }
        case 276: break;
        case 45: 
          {  return symbol(SEMICOLON, ";");  }
        case 277: break;
        case 96: 
          {  return symbol(ADDRESS_ASSIGN, "&=");  }
        case 278: break;
        case 155: 
          {  return symbol(ELSE, "else");  }
        case 279: break;
        case 66: 
          {  return symbol(ADD_ASSIGN, "+=");  }
        case 280: break;
        case 97: 
          {  return symbol(AND_NOT_OP, "&^");  }
        case 281: break;
        case 43: 
          {  return symbol(CURLY_R, "}");  }
        case 282: break;
        case 42: 
          {  return symbol(CURLY_L, "{");  }
        case 283: break;
        case 151: 
          {  return symbol(CASE, "case");  }
        case 284: break;
        case 154: 
          {  return symbol(CHAN, "chan");  }
        case 285: break;
        case 208: 
          {  return symbol(DEFAULT, "default");  }
        case 286: break;
        case 186: 
          {  return symbol(RANGE, "range");  }
        case 287: break;
        case 184: 
          {  return symbol(FALSE, "false");  }
        case 288: break;
        case 30: 
          {  return symbol(ADDRESS, "&");  }
        case 289: break;
        case 98: 
          {  return symbol(CHANNEL_OP, "<-");  }
        case 290: break;
        case 48: 
          {  return symbol(OR_OP, "||");  }
        case 291: break;
        case 44: 
          {  return symbol(COMMA, ",");  }
        case 292: break;
        case 41: 
          {  return symbol(SQRD_R, "]");  }
        case 293: break;
        case 40: 
          {  return symbol(SQRD_L, "[");  }
        case 294: break;
        case 39: 
          {  return symbol(PAR_R, ")");  }
        case 295: break;
        case 38: 
          {  return symbol(PAR_L, "(");  }
        case 296: break;
        case 37: 
          {  return symbol(COLON, ":");  }
        case 297: break;
        case 14: 
          {  return symbol(MINUS, "-");  }
        case 298: break;
        case 32: 
          {  return symbol(ASSIGN, "=");  }
        case 299: break;
        case 101: 
          {  return symbol(EQ_OP, "==");  }
        case 300: break;
        case 105: 
          {  return symbol(NE_OP, "!=");  }
        case 301: break;
        case 124: 
          {  return symbol(FOR, "for");  }
        case 302: break;
        case 129: 
          {  return symbol(VAR, "var");  }
        case 303: break;
        case 145: 
          {  return symbol(MAP, "map");  }
        case 304: break;
        case 2: 
        case 3: 
          {  }
        case 305: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {      return symbolFactory.newSymbol("EOF", EOF, new Location(yyline+1, yycolumn+1), new Location(yyline+1, yycolumn+1));
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
